ktor:
    application:
        modules:
            - me.pavekovt.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost/conflict_manager"
  user: dev_user
  password: dev_password


jwt:
  secret: test
  issuer: confresolv
  audience: all
  realm: main